/**
 * Stub AI provider — lets the whole app run with NO external key.
 *
 * It deliberately does NOT free-form answer. It composes verdict/section text ONLY
 * from the grounded context it is handed, so it exercises the exact same
 * retrieve-then-generate contract a real model will. This keeps the grounding
 * boundary honest during development: swap AI_PROVIDER=anthropic and the harness,
 * logging, and Truth Layer flow are unchanged.
 *
 * Clearly marked as a stub in every output and in the logged model name.
 */
import 'server-only';
import type { AiProvider, GenerateParams, GenerateResult } from './provider';

const EMBED_DIM = 1536;

/** Deterministic pseudo-embedding from text (hashing into a fixed vector). */
function deterministicEmbed(text: string): number[] {
  const v = new Array(EMBED_DIM).fill(0);
  for (let i = 0; i < text.length; i++) {
    const code = text.charCodeAt(i);
    v[(code * 31 + i) % EMBED_DIM] += ((code % 13) - 6) / 6;
  }
  // L2 normalise so cosine distance behaves.
  const norm = Math.sqrt(v.reduce((s, x) => s + x * x, 0)) || 1;
  return v.map((x) => x / norm);
}

export class StubProvider implements AiProvider {
  readonly name = 'stub';

  async generate(params: GenerateParams): Promise<GenerateResult> {
    // Compose strictly from the provided context. No outside knowledge.
    const text =
      `${params.task}\n\n` +
      `[Grounded draft — generated by the stub provider from retrieved, classified data only. ` +
      `Swap AI_PROVIDER to a live model for production phrasing.]\n\n` +
      params.context.trim();
    const inputTokens = Math.ceil((params.system.length + params.context.length + params.task.length) / 4);
    const outputTokens = Math.ceil(text.length / 4);
    return { text, model: 'stub-grounded-v1', inputTokens, outputTokens };
  }

  async embed(text: string): Promise<number[]> {
    return deterministicEmbed(text);
  }
}
